spring:
# 配置thymeleaf
  thymeleaf:
    mode: HTML
    check-template: false
    check-template-location: false
  # 指定环境配置
  profiles:
    active: dev
  web:
    resources:
      add-mappings: true
  jpa:
    open-in-view: true

  messages:
    basename: i18n/messages


