spring:
# 配置数据库
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=utf-8
    username: root
    password: AB123456

# 配置数据库是否可以更新表结构
  jpa:
    hibernate:
      ddl-auto: update
# 配置是否显示SQL语句, true表示显示
    show-sql: true

logging:
  level:
    root: info
    com.yf: debug
# 定义日志文件的存放位置
  file:
    name: log/blog-dev.log

